name: Deploy Web App

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote ssh commands using ssh-key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "==== ĐANG TRIỂN KHAI CẬP NHẬT ỨNG DỤNG ===="

          cd /app

          git config --global --add safe.directory /app
        
          git pull origin main

          docker compose -f /root/chi-tung/ChiTung-compose-app/FastShop/docker-compose.yml down
          docker compose -f /root/chi-tung/ChiTung-compose-app/FastShop/docker-compose.yml up -d --build

          echo "==== ĐÃ RESTART DOCKER COMPOSE THÀNH CÔNG ===="
          
          echo "Chờ 5 giây cho hệ thống ổn định..."
          sleep 5
            
          echo "==== TRẠNG THÁI CÁC CONTAINER DỰ ÁN ===="
          
          docker compose -f /root/chi-tung/ChiTung-compose-app/FastShop/docker-compose.yml ps
            
          echo "==== HỆ THỐNG HOẠT ĐỘNG BÌNH THƯỜNG ===="
